### ISSUE TITLE
not sure how to setup

### ISSUE THREAD

**Issue by marcoluis97** [meyerjo/cartographer-read-pbstream#2]
Greetings @meyerjo 

I do not undestand the setup procedure. Am I supposed to clone Cartographer if I already possess Cartographer_ROS?

**Comment by meyerjo** [comment]
Yeah you need to clone the cartographer repository because you need to run the protobuf conversion on those files.

**Comment by Shadow-Haund** [comment]
Good day to you @meyerjo.
Sorry, if this is something obvious, but I'm too have problems with setup procedure. Then I'm using 
`python` main.py info --inputfile=3rd_floor.pbstream` 
or
`python main.py trajectory --inputfile=3rd_floor.pbstream `

I receive following error:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from pbstream.reader import PBstream_Reader
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/pbstream-0.0.1-py3.8.egg/pbstream/reader.py", line 9, in <module>
ModuleNotFoundError: No module named 'cartographer'

I already installed Cartographer, and trying to get info and trajectories from map, created with my robot, so I'm not sure, why can't it be found. Cartographer was installed following guide from official [site](https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html). Appreciate any hints

Sorry for all mistakes, English is not my native language.

**Comment by bbferka** [comment]
@Shadow-Haund had the same issue, just had to make ``__init__.py`` files in all folders generated by protobuf in the /src/cartographer folder; After that scripts worked

**Comment by jarryxy** [comment]
@bbferka Hello, I also encountered the same problem, I did so according to your prompt, and the problem was still ModuleNotFoundError: No module named 'cartographer.mapping'
![image](https://github.com/meyerjo/cartographer-read-pbstream/assets/56039867/e0615844-78f9-4af3-a3a0-7c85bf6f622c)
